#define PACKAGE_NAME "shish"
#define PACKAGE_TARNAME "shish"
#define PACKAGE_VERSION "0.8"
#define PACKAGE_STRING "shish 0.8"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE_NAME "shish"
#define PACKAGE_TARNAME "shish"
#define PACKAGE_VERSION "0.8"
#define PACKAGE_STRING "shish 0.8"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
