#include "../ast.h"

/* JSON "kind" names, one per union node/arithmetic-op enum value (tree.h).
 * Command-tree nodes are named after POSIX Shell Command Language (2.10)
 * grammar rules; arithmetic-expression nodes (which POSIX defers to C's
 * grammar for) get plain descriptive lower_snake_case names instead. */
const char* const ast_names[] = {
    "simple_command",
    "pipeline",
    "and",
    "or",
    "not",
    "time",
    "list",
    "subshell",
    "brace_group",
    "for_clause",
    "case_clause",
    "case_item",
    "if_clause",
    "while_clause",
    "until_clause",
    "function_definition",
    "word",
    "assignment",
    "redirect",
    "string",
    "command_substitution",
    "parameter_expansion",
    "arithmetic_expansion",
    "number",
    "paren_expr",
    "conditional_expr",
    "logical_or",
    "logical_and",
    "bitwise_or",
    "bitwise_xor",
    "bitwise_and",
    "equal",
    "not_equal",
    "less_than",
    "greater_than",
    "greater_equal",
    "less_equal",
    "shift_left",
    "shift_right",
    "add",
    "subtract",
    "multiply",
    "divide",
    "modulo",
    "exponent",
    "unary_minus",
    "unary_plus",
    "logical_not",
    "bitwise_not",
    "pre_decrement",
    "pre_increment",
    "post_decrement",
    "post_increment",
    "assign",
    "add_assign",
    "sub_assign",
    "mul_assign",
    "div_assign",
    "mod_assign",
    "shl_assign",
    "shr_assign",
    "and_assign",
    "xor_assign",
    "or_assign",
};

const unsigned ast_names_count = sizeof(ast_names) / sizeof(ast_names[0]);
