DIR=$(dirname "${0}")
. "$DIR/common.sh"

## Characterization of word expansion: what a word becomes after tilde, parameter,
## command and arithmetic expansion, field splitting, pathname expansion and quote
## removal. Every expected value is what both dash and bash print for the same
## words (generated by running each case under both; only cases on which they
## agree are listed). It pins the behaviour before the expansion output is moved
## off struct narg (TODO.md, the wordlist plan): the file must pass before and after.

f() { for a in "$@"; do printf "[%s]" "$a"; done; echo; }

D=$(mktemp -d)
touch "$D/xa" "$D/xb" "$D/ya" "$D/.hid"


## splitting

X=$(x="a  b"; f $x)
assert_equal '[a][b]' "$X" 'unquoted $x splits on runs of blanks'

X=$(x="a  b"; f "$x")
assert_equal '[a  b]' "$X" 'quoted $x is one field'

X=$(x=" a b "; f $x)
assert_equal '[a][b]' "$X" 'leading and trailing blanks give no empty fields'

X=$(IFS=,; x="a,b,,c"; f $x)
assert_equal '[a][b][][c]' "$X" 'a non-blank IFS makes empty fields between delimiters'

X=$(IFS=,; x=",a,"; f $x)
assert_equal '[][a]' "$X" 'a leading non-blank delimiter gives one empty field, a trailing one none'

X=$(IFS=", "; x="a, b ,c"; f $x)
assert_equal '[a][b][c]' "$X" 'IFS with blank and non-blank characters'

X=$(IFS=" ,"; x="a , b"; f $x)
assert_equal '[a][b]' "$X" 'a blank next to a non-blank delimiter is absorbed'

X=$(IFS=; x="a b"; f $x)
assert_equal '[a b]' "$X" 'empty IFS disables splitting'

X=$(IFS=:; x="a:b"; f "$x" $x)
assert_equal '[a:b][a][b]' "$X" 'IFS=: splits unquoted, not quoted'

X=$(x=$(printf "a\tb\nc"); f $x)
assert_equal '[a][b][c]' "$X" 'default IFS splits on tab and newline'

X=$(x=; f $x)
assert_equal '' "$X" 'an empty unquoted variable gives no field'

X=$(x=; f "$x")
assert_equal '[]' "$X" 'an empty quoted variable gives one empty field'

X=$(f $unset_var)
assert_equal '' "$X" 'an unset variable gives no field'

X=$(f "$unset_var")
assert_equal '[]' "$X" 'a quoted unset variable gives one empty field'

X=$(f "")
assert_equal '[]' "$X" 'an empty quoted literal is a field'

X=$(f '' '')
assert_equal '[][]' "$X" 'two empty quoted literals are two fields'

X=$(f ""x"")
assert_equal '[x]' "$X" 'empty quotes around nothing'

X=$(x="a b"; f pre$x)
assert_equal '[prea][b]' "$X" 'a variable between literals splits only at its blanks'

X=$(x="a b"; f $x"post")
assert_equal '[a][bpost]' "$X" 'a literal after the variable joins the last field'

X=$(x="a b"; f "pre"$x)
assert_equal '[prea][b]' "$X" 'a quoted prefix joins the first field'

X=$(x="a b"; f a"$x"b)
assert_equal '[aa bb]' "$X" 'a quoted variable between literals stays one field'

X=$(x=a; y="b c"; f $x$y)
assert_equal '[ab][c]' "$X" 'two adjacent variables concatenate before splitting'

X=$(x=" a "; f ""$x"")
assert_equal '[][a][]' "$X" 'IFS whitespace also trims at a quoted/unquoted boundary'


## parameter operators

X=$(f ${x:-a b})
assert_equal '[a][b]' "$X" '${x:-w} with a multi-word default splits'

X=$(f "${x:-a b}")
assert_equal '[a b]' "$X" '${x:-w} quoted is one field'

X=$(x=; f ${x:-w})
assert_equal '[w]' "$X" '${x:-w} with a set empty x uses the default'

X=$(x=; f ${x-w})
assert_equal '' "$X" '${x-w} with a set empty x gives no field'

X=$(f ${x:+w})
assert_equal '' "$X" '${x:+w} with x unset gives no field'

X=$(x=v; f ${x:+a b})
assert_equal '[a][b]' "$X" '${x:+a b} splits when x is set'

X=$(x=v; f "${x:+a b}")
assert_equal '[a b]' "$X" '"${x:+a b}" is one field'

X=$(x=v; f ${x:+"a b"})
assert_equal '[a b]' "$X" 'a quoted word inside ${x:+...} stays one field'

X=$(f ${x:-"a b"})
assert_equal '[a b]' "$X" 'a quoted word inside ${x:-...} stays one field'

X=$(f ${x:--'a  b'})
assert_equal '[-a  b]' "$X" 'single quotes inside ${x:-...} keep the blanks'

X=$(f ${x:-a" b"c})
assert_equal '[a bc]' "$X" 'quotes in the middle of a default'

X=$(x="a b c"; f ${x#a })
assert_equal '[b][c]' "$X" '${x#pat} removes a prefix, then splits'

X=$(x="a b c"; f "${x#a }")
assert_equal '[b c]' "$X" 'quoted ${x#pat} is one field'

X=$(x="a b c"; f ${x%% *})
assert_equal '[a]' "$X" '${x%%pat} removes the longest suffix'

X=$(y="a b"; f ${x:-$y})
assert_equal '[a][b]' "$X" '${x:-$y} splits the substituted value'

X=$(y="a b"; f "${x:-$y}")
assert_equal '[a b]' "$X" '"${x:-$y}" is one field'

X=$(y="a b"; f ${x:-"$y"})
assert_equal '[a b]' "$X" '${x:-"$y"} is one field'

X=$(x=v; y="a b"; f ${x:+$y})
assert_equal '[a][b]' "$X" '${x:+$y} splits when x is set'

X=$(y="b c"; f "${x:-a $y}")
assert_equal '[a b c]' "$X" 'a default mixing literal and variable'

X=$(x=abc; f ${#x})
assert_equal '[3]' "$X" '${#x} is the length'


## positional parameters

X=$(set -- a "b c" ""; f $@)
assert_equal '[a][b][c]' "$X" 'unquoted $@ splits every parameter'

X=$(set -- a "b c" ""; f "$@")
assert_equal '[a][b c][]' "$X" '"$@" keeps one field per parameter'

X=$(set -- a "b c" ""; f $*)
assert_equal '[a][b][c]' "$X" 'unquoted $* splits'

X=$(set -- a "b c" ""; f "$*")
assert_equal '[a b c ]' "$X" '"$*" joins with the first IFS character'

X=$(IFS=:; set -- a b; f "$*")
assert_equal '[a:b]' "$X" '"$*" with IFS=: joins with a colon'

X=$(IFS=; set -- a b; f "$*")
assert_equal '[ab]' "$X" '"$*" with an empty IFS joins without a separator'

X=$(set -- a b; f "$@"x)
assert_equal '[a][bx]' "$X" '"$@"x appends to the last field'

X=$(set -- a b; f x"$@")
assert_equal '[xa][b]' "$X" 'x"$@" prepends to the first field'

X=$(set -- a b; f x"$@"y)
assert_equal '[xa][by]' "$X" 'x"$@"y wraps the first and last fields'

X=$(set --; f "$@")
assert_equal '' "$X" '"$@" with no parameters gives no field'

X=$(set --; f "$@"x)
assert_equal '[x]' "$X" '"$@"x with no parameters gives one field'

X=$(set --; f x"$@"y)
assert_equal '[xy]' "$X" 'x"$@"y with no parameters gives one field'

X=$(set -- a "b c"; f "${@}")
assert_equal '[a][b c]' "$X" '"${@}" is the same as "$@"'

X=$(set -- a b; f "$@" "$@")
assert_equal '[a][b][a][b]' "$X" 'two "$@" in one command'

X=$(set -- "a b"; f "$@")
assert_equal '[a b]' "$X" '"$@" with one multi-word parameter'

X=$(set -- "a b"; f $@)
assert_equal '[a][b]' "$X" 'unquoted $@ with one multi-word parameter splits'

X=$(set -- "" ""; f "$@")
assert_equal '[][]' "$X" '"$@" with two empty parameters'

X=$(set -- "" ""; f $@)
assert_equal '' "$X" 'unquoted $@ with two empty parameters gives no field'

X=$(set -- a b c; f $# ${#})
assert_equal '[3][3]' "$X" '$# counts the parameters'

X=$(set -- a; f "${1}x" "${9}")
assert_equal '[ax][]' "$X" '"${1}x" and an absent "${9}"'

X=$(set -- a "b c"; f "${x:-$@}")
assert_equal '[a][b c]' "$X" '$@ inside a default word'

X=$(set -- a "b c"; f ${x:-$*})
assert_equal '[a][b][c]' "$X" '$* inside a default word, unquoted'


## command and arithmetic substitution

X=$(f $(echo a b))
assert_equal '[a][b]' "$X" 'unquoted $(cmd) splits'

X=$(f "$(echo a b)")
assert_equal '[a b]' "$X" 'quoted $(cmd) is one field'

X=$(f $(printf "a\n\nb"))
assert_equal '[a][b]' "$X" 'blank lines in the output split like blanks'

X=$(f "$(printf "a\n\n")x")
assert_equal '[ax]' "$X" 'trailing newlines are removed inside quotes too'

X=$(f $(echo))
assert_equal '' "$X" 'an empty $(cmd) gives no field'

X=$(f "$(echo)")
assert_equal '[]' "$X" 'a quoted empty $(cmd) is one empty field'

X=$(f x$(echo a b)y)
assert_equal '[xa][by]' "$X" 'a $(cmd) between literals'

X=$(f `echo a b`)
assert_equal '[a][b]' "$X" 'backquotes split like $( )'

X=$(IFS=,; f $(echo a,b))
assert_equal '[a][b]' "$X" 'a custom IFS applies to the output'

X=$(f $((1+2)))
assert_equal '[3]' "$X" 'arithmetic expansion is one word'

X=$(f "$((1+2))"x)
assert_equal '[3x]' "$X" 'arithmetic result joins adjacent text'

X=$(x=" 3 "; f $((x)))
assert_equal '[3]' "$X" 'a variable with blanks inside $(( ))'


## pathname expansion

X=$(cd "$D"; f x*)
assert_equal '[xa][xb]' "$X" 'a pattern matches, sorted'

X=$(cd "$D"; f y*)
assert_equal '[ya]' "$X" 'another prefix'

X=$(cd "$D"; f "x*")
assert_equal '[x*]' "$X" 'a quoted pattern is literal'

X=$(cd "$D"; f x\*)
assert_equal '[x*]' "$X" 'a backslash-escaped star is literal'

X=$(cd "$D"; f *.nomatch)
assert_equal '[*.nomatch]' "$X" 'no match leaves the pattern'

X=$(cd "$D"; f [xy]a)
assert_equal '[xa][ya]' "$X" 'a bracket expression'

X=$(cd "$D"; f .h*)
assert_equal '[.hid]' "$X" 'dotfiles need an explicit dot'

X=$(cd "$D"; f *)
assert_equal '[xa][xb][ya]' "$X" '* skips dotfiles'

X=$(cd "$D"; x='*'; f $x)
assert_equal '[xa][xb][ya]' "$X" 'an unquoted variable is globbed'

X=$(cd "$D"; x='*'; f "$x")
assert_equal '[*]' "$X" 'a quoted variable is not'

X=$(cd "$D"; x='x*'; f $x)
assert_equal '[xa][xb]' "$X" 'a prefix in the variable'

X=$(cd "$D"; f [!x]a)
assert_equal '[ya]' "$X" 'a negated bracket'

X=$(cd "$D"; f "x"*)
assert_equal '[xa][xb]' "$X" 'a quoted prefix before a star'

X=$(cd "$D"; f x'*')
assert_equal '[x*]' "$X" 'a quoted star after a literal'

X=$(cd "$D"; f ?a)
assert_equal '[xa][ya]' "$X" '? matches one character'

X=$(cd "$D"; x=x; f $x*)
assert_equal '[xa][xb]' "$X" 'variable followed by a star'

X=$(cd "$D"; f $(echo x*))
assert_equal '[xa][xb]' "$X" 'the result of $(cmd) is globbed'

X=$(cd "$D"; f "$(echo x*)")
assert_equal '[xa xb]' "$X" 'quoted $(cmd) is not globbed'

X=$(cd "$D"; f ./x*)
assert_equal '[./xa][./xb]' "$X" 'a ./ prefix is kept'

X=$(cd "$D"; set -f; f x*)
assert_equal '[x*]' "$X" 'set -f disables pathname expansion'

X=$(cd "$D"; set -f; set +f; f x*)
assert_equal '[xa][xb]' "$X" 'set -f then set +f'

X=$(cd "$D"; x="p x*"; f $x)
assert_equal '[p][xa][xb]' "$X" 'a glob in the middle of two fields'

X=$(cd "$D"; f nodir/*)
assert_equal '[nodir/*]' "$X" 'a pattern with a slash and no match'


## quoting and escapes

X=$(f a\ b)
assert_equal '[a b]' "$X" 'backslash-blank is one field'

X=$(f "a\ b")
assert_equal '[a\ b]' "$X" 'a backslash is literal in double quotes before a blank'

X=$(f 'a\ b')
assert_equal '[a\ b]' "$X" 'single quotes keep everything'

X=$(f "a\"b")
assert_equal '[a"b]' "$X" 'an escaped double quote'

X=$(x=1; f \$x "\$x" '$x')
assert_equal '[$x][$x][$x]' "$X" 'an escaped dollar'

X=$(f \\ "\\")
assert_equal '[\][\]' "$X" 'an escaped backslash'

X=$(x="a b"; f "'$x'")
assert_equal '['\''a b'\'']' "$X" 'single quotes inside double quotes are literal'

X=$(x="a b"; f '"'"$x"'"')
assert_equal '["a b"]' "$X" 'double quotes inside single quotes are literal'

X=$(f "a  b" c)
assert_equal '[a  b][c]' "$X" 'quoted blank in IFS-less context'


## tilde

X=$(HOME=/h; f ~)
assert_equal '[/h]' "$X" '~ expands to HOME'

X=$(HOME=/h; f ~/x)
assert_equal '[/h/x]' "$X" '~/x'

X=$(HOME=/h; f "~" '~')
assert_equal '[~][~]' "$X" 'a quoted tilde is literal'

X=$(HOME=/h; x=~; f "$x")
assert_equal '[/h]' "$X" 'tilde in an assignment value'

X=$(HOME=/h; x=a:~; f "$x")
assert_equal '[a:/h]' "$X" 'tilde after a colon in an assignment'

X=$(HOME=/h; f a~)
assert_equal '[a~]' "$X" 'tilde not at the start is literal'


## words in other contexts

X=$(x="a b"; for i in $x; do printf "<%s>" "$i"; done; echo)
assert_equal '<a><b>' "$X" 'for splits an unquoted variable'

X=$(x="a b"; for i in "$x" c; do printf "<%s>" "$i"; done; echo)
assert_equal '<a b><c>' "$X" 'for keeps a quoted variable whole'

X=$(for i in; do echo x; done; echo done)
assert_equal 'done' "$X" 'for with an empty list runs nothing'

X=$(set -- a "b c"; for i; do printf "<%s>" "$i"; done; echo)
assert_equal '<a><b c>' "$X" 'for without in uses the parameters'

X=$(set -- a "b c"; for i in "$@"; do printf "<%s>" "$i"; done; echo)
assert_equal '<a><b c>' "$X" 'for over "$@"'

X=$(cd "$D"; for i in x*; do printf "<%s>" "$i"; done; echo)
assert_equal '<xa><xb>' "$X" 'for over a glob'

X=$(x="a b"; case $x in "a b") echo m;; esac)
assert_equal 'm' "$X" 'case matches a quoted word'

X=$(x="a b"; case "$x" in a\ b) echo m;; esac)
assert_equal 'm' "$X" 'case with an escaped blank pattern'

X=$(x="a*"; case abc in $x) echo glob;; esac)
assert_equal 'glob' "$X" 'an unquoted pattern variable globs'

X=$(x="a*"; case abc in "$x") echo m;; *) echo no;; esac)
assert_equal 'no' "$X" 'a quoted pattern variable is literal'

X=$(x="a*"; case "a*" in "$x") echo lit;; esac)
assert_equal 'lit' "$X" 'a quoted pattern variable matches itself'

X=$(x="a  b"; cat <<EOF
$x
EOF
)
assert_equal 'a  b' "$X" 'a here-document keeps the blanks'

X=$(x="a  b"; cat <<"EOF"
$x
EOF
)
assert_equal '$x' "$X" 'a quoted here-document is literal'

X=$(x="a b"; y=$x; f "$y")
assert_equal '[a b]' "$X" 'assignments do not split'

X=$(x="a b"; z=$x true; f "$z")
assert_equal '[]' "$X" 'an assignment prefix does not split the value'

X=$(x="a b"; echo hi > "$D/o $x"; ls "$D" | grep -c "^o a b$"; rm -f "$D/o a b")
assert_equal '1' "$X" 'a redirection target is not split'

rm -rf "$D"

summary
